sudo: required

services:
  - docker

before_install:
  - docker build -t mpayancabrera/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mpayancabrera/react-test npm run test

after_success:
  - docker build -t mpayancabrera/multi-client ./client
  - docker build -t mpayancabrera/multi-nginx ./nginx
  - docker build -t mpayancabrera/multi-server ./server
  - docker build -t mpayancabrera/multi-worker ./worker
  #log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push mpayancabrera/multi-client
  - docker push mpayancabrera/multi-nginx
  - docker push mpayancabrera/multi-server
  - docker push mpayancabrera/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-902137919815
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

